/*
Copyright (C) 1996-1997 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

#if NATIVE_GAME
// ---------------------------------------------------------------------------
// NATIVE_GAME=1: use native C entity types from game_types.h instead of
// the QC VM entvars_t / progs.dat layout.
// ---------------------------------------------------------------------------
// common.h (already included by quakedef.h before us) defines link_t and
// entity_state_t is defined inline in quakedef.h. Set guards so game_types.h
// doesn't redefine them.
#define LINK_T_DEFINED
#define ENTITY_STATE_T_DEFINED
#include "game_api.h"    // edict_t forward decl, game_globals_t
#include "game_types.h"  // full edict_t with native C types

extern char           *pr_strings;
extern int             pr_edict_size;
extern game_globals_t  game_globals;
extern unsigned short  pr_crc;

// Minimal globalvars_t stub -- engine code still references pr_global_struct
typedef struct {
	int   pad[28];
	int   self, other, world;
	float time, frametime, force_retouch;
	int   mapname_unused;
	float deathmatch, coop, teamplay, serverflags;
	float total_secrets, total_monsters, found_secrets, killed_monsters;
	float parm1, parm2, parm3, parm4, parm5, parm6, parm7, parm8;
	float parm9, parm10, parm11, parm12, parm13, parm14, parm15, parm16;
	float v_forward[3], v_up[3], v_right[3];
	float trace_allsolid, trace_startsolid, trace_fraction;
	float trace_endpos[3], trace_plane_normal[3];
	float trace_plane_dist;
	int   trace_ent;
	float trace_inopen, trace_inwater;
	int   msg_entity;
} globalvars_t;
extern globalvars_t *pr_global_struct;

void PR_Init(void);
void PR_LoadProgs(void);
void PR_ExecuteProgram(int fnum);   /* never called in NATIVE_GAME=1 */

edict_t *ED_Alloc(void);
void     ED_Free(edict_t *ed);
char    *ED_NewString(const char *string);
void     ED_Print(edict_t *ed);
char    *ED_ParseEdict(char *data, edict_t *ent);
void     ED_LoadFromFile(char *data);
void     ED_PrintEdicts(void);
void     ED_PrintNum(int ent);

edict_t *EDICT_NUM(int n);
int      NUM_FOR_EDICT(edict_t *e);

#define NEXT_EDICT(e)    ((edict_t *)((byte *)(e) + pr_edict_size))
/* In NATIVE_GAME=1, entity-link fields are edict_t* not int offsets.
 * PROG_TO_EDICT is a no-op cast: the field IS already an edict_t*.
 * EDICT_TO_PROG stores a byte offset into the stub pr_global_struct->self (int),
 * but those reads are only used in pre-NATIVE_GAME dispatch code that is
 * immediately superseded by game_globals.self writes. */
#define EDICT_TO_PROG(e) ((int)((byte *)(e) - (byte *)sv.edicts))
#define PROG_TO_EDICT(e) ((edict_t *)(e))
#define EDICT_FROM_AREA(l) STRUCT_FROM_LINK(l,edict_t,area)

/* For compat with GetEdictFieldValue calls in debug code */
typedef union { float _float; int _int; char *string; } eval_t;
static inline eval_t *GetEdictFieldValue(edict_t *ed, char *field) {
	(void)ed; (void)field; return (eval_t*)0;
}

/* Dummy to satisfy any remaining references */
void PR_RunError(char *error, ...);
void PR_Profile_f(void);

#else  /* NATIVE_GAME=0 — original VM path */

#include "pr_comp.h"			// defs shared with qcc
#include "progdefs.h"			// generated by program cdefs

typedef union eval_s
{
	string_t		string;
	float			_float;
	float			vector[3];
	func_t			function;
	int				_int;
	int				edict;
} eval_t;

#define	MAX_ENT_LEAFS	16
typedef struct edict_s
{
	qboolean	free;
	link_t		area;				// linked to a division node or leaf

	int			num_leafs;
	short		leafnums[MAX_ENT_LEAFS];

	entity_state_t	baseline;

	float		freetime;			// sv.time when the object was freed
	entvars_t	v;					// C exported fields from progs
// other fields from progs come immediately after
} edict_t;
#define	EDICT_FROM_AREA(l) STRUCT_FROM_LINK(l,edict_t,area)

//============================================================================

extern	dprograms_t		*progs;
extern	dfunction_t		*pr_functions;
extern	char			*pr_strings;
extern	ddef_t			*pr_globaldefs;
extern	ddef_t			*pr_fielddefs;
extern	dstatement_t	*pr_statements;
extern	globalvars_t	*pr_global_struct;
extern	float			*pr_globals;			// same as pr_global_struct

extern	int				pr_edict_size;	// in bytes

//============================================================================

void PR_Init (void);

void PR_ExecuteProgram (func_t fnum);
void PR_LoadProgs (void);

void PR_Profile_f (void);

edict_t *ED_Alloc (void);
void ED_Free (edict_t *ed);

char	*ED_NewString (char *string);
// returns a copy of the string allocated from the server's string heap

void ED_Print (edict_t *ed);
void ED_Write (FILE *f, edict_t *ed);
char *ED_ParseEdict (char *data, edict_t *ent);

void ED_WriteGlobals (FILE *f);
void ED_ParseGlobals (char *data);

void ED_LoadFromFile (char *data);

//define EDICT_NUM(n) ((edict_t *)(sv.edicts+ (n)*pr_edict_size))
//define NUM_FOR_EDICT(e) (((byte *)(e) - sv.edicts)/pr_edict_size)

edict_t *EDICT_NUM(int n);
int NUM_FOR_EDICT(edict_t *e);

#define	NEXT_EDICT(e) ((edict_t *)( (byte *)e + pr_edict_size))

#define	EDICT_TO_PROG(e) ((byte *)e - (byte *)sv.edicts)
#define PROG_TO_EDICT(e) ((edict_t *)((byte *)sv.edicts + e))

//============================================================================

#define	G_FLOAT(o) (pr_globals[o])
#define	G_INT(o) (*(int *)&pr_globals[o])
#define	G_EDICT(o) ((edict_t *)((byte *)sv.edicts+ *(int *)&pr_globals[o]))
#define G_EDICTNUM(o) NUM_FOR_EDICT(G_EDICT(o))
#define	G_VECTOR(o) (&pr_globals[o])
#define	G_STRING(o) (pr_strings + *(string_t *)&pr_globals[o])
#define	G_FUNCTION(o) (*(func_t *)&pr_globals[o])

#define	E_FLOAT(e,o) (((float*)&e->v)[o])
#define	E_INT(e,o) (*(int *)&((float*)&e->v)[o])
#define	E_VECTOR(e,o) (&((float*)&e->v)[o])
#define	E_STRING(e,o) (pr_strings + *(string_t *)&((float*)&e->v)[o])

extern	int		type_size[8];

typedef void (*builtin_t) (void);
extern	builtin_t *pr_builtins;
extern int pr_numbuiltins;

extern int		pr_argc;

extern	qboolean	pr_trace;
extern	dfunction_t	*pr_xfunction;
extern	int			pr_xstatement;

extern	unsigned short		pr_crc;

void PR_RunError (char *error, ...);

void ED_PrintEdicts (void);
void ED_PrintNum (int ent);

eval_t *GetEdictFieldValue(edict_t *ed, char *field);

#endif /* NATIVE_GAME */

