#!/bin/sh
# build_shaders.sh -- compile GLSL shaders to SPIR-V + MSL, emit a single
# header with byte arrays + source strings for the runtime to pick from.
#
# Inputs:  shaders/*.glsl (under arg 1)
# Output:  arg 2 -- a single .h file with palette_{vert,frag}_{spv,msl}
# Tools:   glslangValidator (SPIR-V), spirv-cross (MSL translation)
#
# Both must be on PATH. macOS: brew install glslang spirv-cross.

set -eu

shader_dir="$1"
out_h="$2"
tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT

compile_one() {
    stage="$1"      # vert | frag
    src="$shader_dir/palette.$stage.glsl"
    spv="$tmp_dir/palette.$stage.spv"
    msl="$tmp_dir/palette.$stage.msl"

    glslangValidator -V -S "$stage" -o "$spv" "$src" >/dev/null
    # MSL 3.0 covers macOS 13+ / iOS 16+. SDL_GPU's Metal backend handles older
    # devices via Metal's own runtime compilation, so requiring a recent MSL is
    # safe for our supported platforms.
    # --flip-vert-y: Metal's NDC has Y pointing up; spirv-cross emits a Y-flip
    # on gl_Position.y so the GLSL source (Vulkan Y-down) renders the same on
    # both backends.
    spirv-cross --msl --msl-version 30000 --flip-vert-y "$spv" --output "$msl"
}

compile_one vert
compile_one frag

# Emit the header. xxd -i produces "unsigned char NAME[] = { ... }; unsigned int
# NAME_len = ..." for binary blobs. For MSL strings we use sed to quote each
# line, embedded as a single string literal terminated by \0.
{
    printf '// Auto-generated by scripts/build_shaders.sh -- do not edit.\n'
    printf '// Source: shaders/palette.{vert,frag}.glsl\n'
    printf '#pragma once\n'
    printf '#include <stdint.h>\n\n'

    cd "$tmp_dir"
    xxd -i palette.vert.spv | sed -e 's/unsigned char palette_vert_spv/static const uint8_t palette_vert_spv/' -e 's/unsigned int palette_vert_spv_len/static const unsigned int palette_vert_spv_size/'
    printf '\n'
    xxd -i palette.frag.spv | sed -e 's/unsigned char palette_frag_spv/static const uint8_t palette_frag_spv/' -e 's/unsigned int palette_frag_spv_len/static const unsigned int palette_frag_spv_size/'
    printf '\n'

    printf 'static const char palette_vert_msl[] =\n'
    sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/    "/' -e 's/$/\\n"/' palette.vert.msl
    printf ';\n\n'

    printf 'static const char palette_frag_msl[] =\n'
    sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/    "/' -e 's/$/\\n"/' palette.frag.msl
    printf ';\n'
} > "$out_h"

printf 'shaders: wrote %s (%d bytes)\n' "$out_h" "$(wc -c < "$out_h")"
