#!/bin/sh
# build_shaders.sh -- compile GLSL shaders to SPIR-V + MSL, emit a single
# header with byte arrays + source strings for the runtime to pick from.
#
# Inputs:  $shader_dir/<stem>.{vert,frag}.glsl for every stem listed below
# Output:  arg 2 -- a single .h file with <stem>_{vert,frag}_{spv,msl}
# Tools:   glslangValidator (SPIR-V), spirv-cross (MSL translation)
#
# Both must be on PATH. macOS: brew install glslang spirv-cross.

set -eu

shader_dir="$1"
out_h="$2"

# Shaders to compile. To add a new pair, drop $shader_dir/<name>.{vert,frag}.glsl
# in place, add the stem here, and declare it as a file input in build.zig.
stems="palette rect_overlay"

tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT

compile_one() {
    stem="$1"
    stage="$2"      # vert | frag
    src="$shader_dir/$stem.$stage.glsl"
    spv="$tmp_dir/$stem.$stage.spv"
    msl="$tmp_dir/$stem.$stage.msl"

    glslangValidator -V -S "$stage" -o "$spv" "$src" >/dev/null
    # MSL 3.0 covers macOS 13+ / iOS 16+. SDL_GPU's Metal backend handles older
    # devices via Metal's own runtime compilation, so requiring a recent MSL is
    # safe for our supported platforms.
    # --flip-vert-y: Metal's NDC has Y pointing up; spirv-cross emits a Y-flip
    # on gl_Position.y so the GLSL source (Vulkan Y-down) renders the same on
    # both backends.
    spirv-cross --msl --msl-version 30000 --flip-vert-y "$spv" --output "$msl"
}

for stem in $stems; do
    compile_one "$stem" vert
    compile_one "$stem" frag
done

# Emit the header. xxd -i produces "unsigned char NAME[] = { ... }; unsigned int
# NAME_len = ..." for binary blobs. For MSL strings we use sed to quote each
# line, embedded as a single string literal terminated by \0.
emit_stem() {
    stem="$1"
    cd "$tmp_dir"
    xxd -i "$stem.vert.spv" | sed -e "s/unsigned char ${stem}_vert_spv/static const uint8_t ${stem}_vert_spv/" -e "s/unsigned int ${stem}_vert_spv_len/static const unsigned int ${stem}_vert_spv_size/"
    printf '\n'
    xxd -i "$stem.frag.spv" | sed -e "s/unsigned char ${stem}_frag_spv/static const uint8_t ${stem}_frag_spv/" -e "s/unsigned int ${stem}_frag_spv_len/static const unsigned int ${stem}_frag_spv_size/"
    printf '\n'

    printf 'static const char %s_vert_msl[] =\n' "$stem"
    sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/    "/' -e 's/$/\\n"/' "$stem.vert.msl"
    printf ';\n\n'

    printf 'static const char %s_frag_msl[] =\n' "$stem"
    sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/    "/' -e 's/$/\\n"/' "$stem.frag.msl"
    printf ';\n\n'
}

{
    printf '// Auto-generated by scripts/build_shaders.sh -- do not edit.\n'
    printf '// Source: shaders/{%s}.{vert,frag}.glsl\n' "$(echo $stems | tr ' ' ',')"
    printf '#pragma once\n'
    printf '#include <stdint.h>\n\n'

    for stem in $stems; do
        emit_stem "$stem"
    done
} > "$out_h"

printf 'shaders: wrote %s (%d bytes)\n' "$out_h" "$(wc -c < "$out_h")"
