//! build_shaders.zig -- compile GLSL shaders to SPIR-V (+ MSL when spirv-cross
//! is available) and emit a single C header with byte arrays + source strings
//! for the runtime (vid_sdl.c) to pick from. Cross-platform replacement for the
//! old scripts/build_shaders.sh: pure Zig orchestration, no /bin/sh, no xxd/sed.
//!
//! Usage:  build_shaders <shader_dir> <out_header> <stem...>
//!   For each stem, reads <shader_dir>/<stem>.{vert,frag}.glsl and writes
//!   <stem>_{vert,frag}_{spv,msl} symbols into <out_header>.
//!
//! Vertex shaders bake the SDL_GPU Y-up-NDC / Y-down-texcoord handling into
//! v_uv directly, so MSL is generated WITHOUT --flip-vert-y (a per-backend flip
//! would re-invert Metal). See shaders/palette.vert.glsl.
//!
//! External tools (resolved on PATH):
//!   glslangValidator  -- GLSL -> SPIR-V (required).
//!   spirv-cross       -- SPIR-V -> MSL (optional). When absent the MSL strings
//!                        are emitted empty: the Windows/Linux Vulkan path uses
//!                        only the SPIR-V, so the build still compiles & runs;
//!                        regenerate on a macOS checkout (brew install
//!                        spirv-cross) to fill in the Metal path.

const std = @import("std");
const Io = std.Io;
const Dir = std.Io.Dir;
const Allocator = std.mem.Allocator;

const stages = [_][]const u8{ "vert", "frag" };

pub fn main(init: std.process.Init) !void {
    const a = init.arena.allocator();
    const io = init.io;
    const args = try init.minimal.args.toSlice(a);
    if (args.len < 4) {
        std.debug.print("usage: build_shaders <shader_dir> <out_header> <stem...>\n", .{});
        return error.BadArgs;
    }
    const shader_dir = args[1];
    const out_h = args[2];
    const stems = args[3..];

    const scratch = std.fs.path.dirname(out_h) orelse ".";

    // Probe spirv-cross once. Absent -> stub MSL (see file header). Stay silent
    // on success: this runs as a Zig `.check` Run step, which flags ANY child
    // stderr as a build warning, so info goes nowhere and only errors print.
    const have_msl = toolAvailable(a, io, &.{ "spirv-cross", "--version" });

    var out: std.ArrayList(u8) = .empty;
    defer out.deinit(a);

    try app(&out, a, "// Auto-generated by tools/build_shaders.zig -- do not edit.\n", .{});
    try app(&out, a, "// Source: shaders/<stem>.{{vert,frag}}.glsl\n", .{});
    try app(&out, a, "#pragma once\n#include <stdint.h>\n\n", .{});

    for (stems) |stem| {
        for (stages) |stage| {
            const src = try std.fmt.allocPrint(a, "{s}/{s}.{s}.glsl", .{ shader_dir, stem, stage });
            const spv_path = try std.fmt.allocPrint(a, "{s}/{s}.{s}.spv", .{ scratch, stem, stage });

            // GLSL -> SPIR-V.
            try mustRun(a, io, &.{ "glslangValidator", "-V", "-S", stage, "-o", spv_path, src });
            const spv = try readFile(a, io, spv_path);

            // SPIR-V byte array + size, matching the symbol names vid_sdl.c uses.
            const sym = try std.fmt.allocPrint(a, "{s}_{s}_spv", .{ stem, stage });
            try emitByteArray(&out, a, sym, spv);

            // SPIR-V -> MSL (optional). No --flip-vert-y: SDL_GPU exposes a
            // uniform Y-up NDC across backends, so the vertex shaders bake the
            // Y handling into v_uv directly (see palette.vert.glsl). A
            // per-backend flip here would re-invert the Metal path.
            const msl_sym = try std.fmt.allocPrint(a, "{s}_{s}_msl", .{ stem, stage });
            if (have_msl) {
                const msl_path = try std.fmt.allocPrint(a, "{s}/{s}.{s}.msl", .{ scratch, stem, stage });
                try mustRun(a, io, &.{ "spirv-cross", "--msl", "--msl-version", "30000", spv_path, "--output", msl_path });
                try emitString(&out, a, msl_sym, try readFile(a, io, msl_path));
            } else {
                try emitString(&out, a, msl_sym, "");
            }
        }
    }

    const f = try Dir.cwd().createFile(io, out_h, .{});
    defer f.close(io);
    try f.writePositionalAll(io, out.items, 0);
}

/// `static const uint8_t <name>[] = { ... };` + `static const unsigned int <name>_size = N;`
/// xxd -i layout: 12 bytes per line.
fn emitByteArray(out: *std.ArrayList(u8), a: Allocator, name: []const u8, bytes: []const u8) !void {
    try app(out, a, "static const uint8_t {s}[] = {{\n", .{name});
    const hex = "0123456789abcdef";
    var i: usize = 0;
    while (i < bytes.len) : (i += 1) {
        if (i % 12 == 0) try out.appendSlice(a, "  ");
        const b = bytes[i];
        try out.appendSlice(a, &[_]u8{ '0', 'x', hex[b >> 4], hex[b & 0xf], ',' });
        try out.append(a, if ((i + 1) % 12 == 0) '\n' else ' ');
    }
    if (bytes.len % 12 != 0) try out.append(a, '\n');
    try app(out, a, "}};\n", .{});
    try app(out, a, "static const unsigned int {s}_size = {d};\n\n", .{ name, bytes.len });
}

/// `static const char <name>[] = "...";` -- each source line a quoted literal
/// with a trailing \n, backslash/quote escaped (the old sed step).
fn emitString(out: *std.ArrayList(u8), a: Allocator, name: []const u8, text: []const u8) !void {
    if (text.len == 0) {
        try app(out, a, "static const char {s}[] = \"\";\n\n", .{name});
        return;
    }
    try app(out, a, "static const char {s}[] =\n", .{name});
    var it = std.mem.splitScalar(u8, text, '\n');
    while (it.next()) |line| {
        // Drop the empty segment a trailing newline leaves behind.
        if (line.len == 0 and it.rest().len == 0) break;
        try out.appendSlice(a, "    \"");
        for (line) |c| switch (c) {
            '\\' => try out.appendSlice(a, "\\\\"),
            '"' => try out.appendSlice(a, "\\\""),
            '\r' => {},
            else => try out.append(a, c),
        };
        try out.appendSlice(a, "\\n\"\n");
    }
    try app(out, a, ";\n\n", .{});
}

fn app(out: *std.ArrayList(u8), a: Allocator, comptime fmt: []const u8, args: anytype) !void {
    const s = try std.fmt.allocPrint(a, fmt, args);
    try out.appendSlice(a, s);
}

fn readFile(a: Allocator, io: Io, path: []const u8) ![]u8 {
    const f = try Dir.cwd().openFile(io, path, .{});
    defer f.close(io);
    const st = try f.stat(io);
    const data = try a.alloc(u8, @intCast(st.size));
    _ = try f.readPositionalAll(io, data, 0);
    return data;
}

/// Run a command, failing the build on spawn error or non-zero exit.
fn mustRun(a: Allocator, io: Io, argv: []const []const u8) !void {
    const res = std.process.run(a, io, .{ .argv = argv }) catch |err| {
        std.debug.print("build_shaders: failed to spawn '{s}': {s}\n", .{ argv[0], @errorName(err) });
        return error.ToolSpawnFailed;
    };
    const ok = switch (res.term) {
        .exited => |code| code == 0,
        else => false,
    };
    if (!ok) {
        std.debug.print("build_shaders: '{s}' failed:\n{s}\n{s}\n", .{ argv[0], res.stdout, res.stderr });
        return error.ToolFailed;
    }
}

/// True if a command spawns and exits cleanly (used to probe for spirv-cross).
fn toolAvailable(a: Allocator, io: Io, argv: []const []const u8) bool {
    const res = std.process.run(a, io, .{ .argv = argv }) catch return false;
    return switch (res.term) {
        .exited => |code| code == 0,
        else => false,
    };
}
