// vid_sdl.c -- SDL3 video driver replacing vid_win.c.
//
// Software framebuffer (8-bit palettized) -> GPU R8 texture -> SDL_GPU
// graphics pipeline running palette.frag.glsl -> swapchain present.
//
// The CPU side of the rasterizer is unchanged from the SDL_Renderer path:
// engine code writes palette indices into vid.buffer and palette-slot ids
// into vid_palette_id at vid_super_w stride. VID_Update uploads both as R8
// GPU textures, plus the 3×256 RGBA8 palette LUT, and the fragment shader
// does the dependent lookup that used to run on the CPU. ImGui composites
// on top via the SDL_GPU3 backend in the same render pass.

#include <SDL3/SDL.h>
#include "quakedef.h"
#include "winquake.h"
#include "imgui_layer.h"
#include "r_bbox.h"
#include "r_paths.h"
#include "vid_palette.h"
#include "debug_lines.h"
#include "crop_screenshot.h"
#include "video_record.h"
#include "perf.h"
#include "editor.h"     // Editor_IsOpen() — game vs editor in the window title

// Compiled palette-expand shaders (SPIR-V bytecode + MSL source string),
// auto-generated by tools/build_shaders.zig from shaders/palette.{vert,frag}.glsl.
#include "palette_shaders.h"

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"

/* Defined in clipboard.c — copy a PNG to the system clipboard.
   We forward-declare rather than #include to keep vid_sdl.c's
   header surface small. */
extern int  Clipboard_SetPNG(const void *bytes, size_t size);

// Menu helpers from menu.c (no shared header)
extern void M_Print(int cx, int cy, char *str);
extern void M_PrintWhite(int cx, int cy, char *str);
extern void M_DrawPic(int x, int y, qpic_t *pic);
extern void M_DrawCharacter(int cx, int line, int num);
extern void M_Menu_Options_f(void);

// ---------------------------------------------------------------------------
// Globals that Win32 platform files normally define
// ---------------------------------------------------------------------------
HINSTANCE global_hInstance = NULL;
int       global_nCmdShow  = 0;
HWND      mainwindow       = NULL;

qboolean ActiveApp   = true;
qboolean Minimized   = false;
qboolean WinNT       = false;
qboolean block_drawing = false;

modestate_t modestate = MS_WINDOWED;

cvar_t _windowed_mouse = {"_windowed_mouse", "1", true};

viddef_t vid;

// d_8to24table[256]: slot 0 Quake palette. Engine code reads this directly
// via the `extern unsigned d_8to24table[256]` declaration in vid.h.
unsigned    d_8to24table[256];
unsigned short d_8to16table[256]; // unused in software but declared in vid.h

// Multi-palette LUT used only by VID_Update.
// vid_lut[VID_PAL_QUAKE] mirrors d_8to24table[]; slots 1+ are filled on demand.
static unsigned vid_lut[VID_NUM_PALETTES][256];

void (*vid_menudrawfn)(void) = NULL;
void (*vid_menukeyfn)(int key) = NULL;

static SDL_Window    *sdl_window  = NULL;

// ---------------------------------------------------------------------------
// SDL_GPU state
// ---------------------------------------------------------------------------
//
// Per-frame textures:
//   gpu_fb_tex        R8       (render_w x render_h)   -- palette indices
//   gpu_palette_id_tex R8      (render_w x render_h)   -- per-pixel slot (0..N-1)
//   gpu_palette_tex   RGBA8    (256 x VID_NUM_PALETTES) -- the LUT itself
//
// All three are sampled via a single nearest-clamp sampler. The pipeline
// renders one fullscreen triangle (no vertex buffer needed; gl_VertexIndex
// drives positions in palette.vert.glsl).
//
// The framebuffer + palette-id textures are re-uploaded every frame via a
// dynamic transfer buffer. The palette LUT is uploaded only when a palette
// slot changes (vid_load_aux_palette / build_palette_slot mark gpu_lut_dirty).
static SDL_GPUDevice           *gpu_device        = NULL;
static SDL_GPUGraphicsPipeline *gpu_pipeline      = NULL;
static SDL_GPUGraphicsPipeline *gpu_rect_pipeline = NULL;  // crop-screenshot overlay
static SDL_GPUSampler          *gpu_sampler       = NULL;
static SDL_GPUTexture          *gpu_fb_tex        = NULL;
static SDL_GPUTexture          *gpu_palette_id_tex = NULL;
static SDL_GPUTexture          *gpu_palette_tex   = NULL;
static SDL_GPUTransferBuffer   *gpu_frame_xfer    = NULL; // sized to fb+palette_id
static SDL_GPUTransferBuffer   *gpu_palette_xfer  = NULL; // 256 * N * 4 bytes
static int                      gpu_fb_tex_w      = 0;
static int                      gpu_fb_tex_h      = 0;
static int                      gpu_lut_dirty     = 1;
static SDL_GPUTexture          *gpu_scene_tex     = NULL;
static int                      gpu_scene_w       = 0;
static int                      gpu_scene_h       = 0;
static SDL_GPUTextureFormat     gpu_swapchain_format = SDL_GPU_TEXTUREFORMAT_INVALID;

// VID_RequestGPUScreenshot sets the pending flag; the actual download happens
// next frame inside gpu_render_frame. Mutex-free: writer is the MCP thread,
// reader is the main thread; volatile + a fixed-size path buffer avoid races.
static volatile int             gpu_screenshot_pending = 0;
static char                     gpu_screenshot_path[512];
static SDL_GPUTransferBuffer   *gpu_readback_xfer  = NULL;
static int                      gpu_readback_size  = 0;

static int vid_scale_active = 3;               // render scale actually applied
static cvar_t vid_scale = {"vid_scale", "0", true}; // 0=auto, 1-4=explicit; archived

static int vid_window_scale_active = 3;        // window-size scale actually applied
static cvar_t vid_window_scale = {"vid_window_scale", "0", true};

// Last-saved window position; -1 = unset, let the OS pick.
static cvar_t vid_window_x = {"vid_window_x", "-1", true};
static cvar_t vid_window_y = {"vid_window_y", "-1", true};
// Last-saved window size; -1 = unset, derive from vid_window_scale.
static cvar_t vid_window_w = {"vid_window_w", "-1", true};
static cvar_t vid_window_h = {"vid_window_h", "-1", true};

static int vid_supersample_active = 1;
static cvar_t vid_supersample = {"vid_supersample", "1", true};

// Scanlines (CRT overlay). All three are persisted to config.cfg.
static cvar_t vid_scanlines          = {"vid_scanlines",          "0",   true};
static cvar_t vid_scanline_intensity = {"vid_scanline_intensity", "0.5", true};
static cvar_t vid_scanline_size      = {"vid_scanline_size",      "1",   true};

#define VID_NUM_SCALES 4
// Cursor positions:
//   0..3   supersample
//   4..7   render scale
//   8..11  window scale
//   12     scanlines toggle
//   13     scanline intensity
//   14     scanline size
//   15     save
#define VID_MENU_SS_BASE          0
#define VID_MENU_RENDER_BASE      (VID_NUM_SCALES)
#define VID_MENU_WINDOW_BASE      (VID_NUM_SCALES * 2)
#define VID_MENU_SCANLINES_POS    (VID_NUM_SCALES * 3)
#define VID_MENU_SL_INTENSITY_POS (VID_NUM_SCALES * 3 + 1)
#define VID_MENU_SL_SIZE_POS      (VID_NUM_SCALES * 3 + 2)
#define VID_MENU_SAVE_POS         (VID_NUM_SCALES * 3 + 3)
#define VID_MENU_ITEMS            (VID_MENU_SAVE_POS + 1)
static const int    vid_scale_factors[VID_NUM_SCALES] = {1, 2, 3, 4};
static const char  *vid_scale_labels[VID_NUM_SCALES]  = {
    "1x  320x200",
    "2x  640x400",
    "3x  960x600",
    "4x  1280x800"
};
static const char  *vid_ss_labels[VID_NUM_SCALES] = {
    "1x  (off)",
    "2x",
    "3x",
    "4x"
};
static int vid_menu_cursor = 0;

#define VID_WIDTH  320
#define VID_HEIGHT 200
#define VID_RENDER_MAX_W (VID_WIDTH  * 8)  /* 2560 — render_scale·SS up to 8 */
#define VID_RENDER_MAX_H (VID_HEIGHT * 8)  /* 1600 */

static int vid_render_w = VID_WIDTH;
static int vid_render_h = VID_HEIGHT;
static int vid_super_w  = VID_WIDTH;   /* = vid_render_w * vid_supersample_active */
static int vid_super_h  = VID_HEIGHT;

static byte vid_buffer[VID_RENDER_MAX_W * VID_RENDER_MAX_H];
byte vid_palette_id[VID_RENDER_MAX_W * VID_RENDER_MAX_H];  /* declared in vid_palette.h */

// ---------------------------------------------------------------------------
// Palette helpers
// ---------------------------------------------------------------------------

static void build_palette_slot(int slot, unsigned char *palette);  // fwd
static void build_palette_slot_impl(int slot, unsigned char *palette);
static void build_palette_slot(int slot, unsigned char *palette) {
    build_palette_slot_impl(slot, palette);
    gpu_lut_dirty = 1;
}
static void build_palette_slot_impl(int slot, unsigned char *palette)
{
    unsigned *lut = vid_lut[slot];
    for (int i = 0; i < 256; i++)
    {
        unsigned r = palette[i*3 + 0];
        unsigned g = palette[i*3 + 1];
        unsigned b = palette[i*3 + 2];
        // SDL_PIXELFORMAT_ARGB8888: 0xAARRGGBB as uint32 (LE stored as B,G,R,A)
        lut[i] = 0xFF000000u | (r << 16) | (g << 8) | b;
    }
    // 255 is transparent in every palette slot
    lut[255] = 0;
    // Slot 0 also backs the engine-visible d_8to24table[256].
    if (slot == VID_PAL_QUAKE)
        memcpy(d_8to24table, lut, 256 * sizeof(unsigned));
}

static void build_palette(unsigned char *palette)
{
    build_palette_slot(VID_PAL_QUAKE, palette);
}

// Load an auxiliary palette from a .lmp file (768 bytes: 256 * RGB) into the
// given vid_lut slot. Tolerates a missing file — slot stays zero-filled and a
// warning is printed. COM_LoadHunkFile is declared in common.h (via quakedef.h).
static void vid_load_aux_palette(int slot, const char *qpath)
{
    byte *data = COM_LoadHunkFile((char *)qpath);
    if (!data)
    {
        Con_Printf("vid_load_aux_palette: %s missing; slot %d zero-filled\n",
                   qpath, slot);
        return;
    }
    build_palette_slot(slot, data);
    // COM_LoadHunkFile data is owned by the hunk; nothing to free here.
}

void VID_SetPalette(unsigned char *palette)   { build_palette(palette); }
void VID_ShiftPalette(unsigned char *palette) { build_palette(palette); }

// ---------------------------------------------------------------------------
// Live resolution switch
// ---------------------------------------------------------------------------

// Apply a (render_scale, supersample) pair. The framebuffer/engine state
// (vid.width etc.) reflects render_scale * ss; the SDL texture and the
// logical-presentation size stay at render_scale (chunky display grid).
// `ss` is clamped so render_scale * ss <= 8.
// ---------------------------------------------------------------------------
// SDL_GPU helpers
// ---------------------------------------------------------------------------

static void gpu_upload_palette(SDL_GPUCommandBuffer *cmd) {
    if (!gpu_lut_dirty || !gpu_device) return;
    // Pack vid_lut (ARGB8888, 3 slots × 256) into RGBA8 byte order for the
    // R8G8B8A8_UNORM LUT texture.
    void *mapped = SDL_MapGPUTransferBuffer(gpu_device, gpu_palette_xfer, true);
    if (mapped) {
        uint8_t *dst = (uint8_t *)mapped;
        for (int slot = 0; slot < VID_NUM_PALETTES; slot++) {
            for (int idx = 0; idx < 256; idx++) {
                unsigned c = vid_lut[slot][idx];
                dst[0] = (uint8_t)(c >> 16);
                dst[1] = (uint8_t)(c >>  8);
                dst[2] = (uint8_t)(c >>  0);
                dst[3] = 0xff;
                dst += 4;
            }
        }
        SDL_UnmapGPUTransferBuffer(gpu_device, gpu_palette_xfer);
    }

    SDL_GPUCopyPass *copy = SDL_BeginGPUCopyPass(cmd);
    SDL_GPUTextureTransferInfo src_info = {0};
    src_info.transfer_buffer = gpu_palette_xfer;
    src_info.offset          = 0;
    src_info.pixels_per_row  = 256;
    src_info.rows_per_layer  = VID_NUM_PALETTES;
    SDL_GPUTextureRegion dst_region = {0};
    dst_region.texture = gpu_palette_tex;
    dst_region.w = 256; dst_region.h = VID_NUM_PALETTES; dst_region.d = 1;
    SDL_UploadToGPUTexture(copy, &src_info, &dst_region, false);
    SDL_EndGPUCopyPass(copy);
    gpu_lut_dirty = 0;
}

static void gpu_create_frame_textures(int w, int h) {
    if (gpu_fb_tex)         SDL_ReleaseGPUTexture       (gpu_device, gpu_fb_tex);
    if (gpu_palette_id_tex) SDL_ReleaseGPUTexture       (gpu_device, gpu_palette_id_tex);
    if (gpu_frame_xfer)     SDL_ReleaseGPUTransferBuffer(gpu_device, gpu_frame_xfer);

    SDL_GPUTextureCreateInfo tex_info = {0};
    tex_info.type                 = SDL_GPU_TEXTURETYPE_2D;
    tex_info.format               = SDL_GPU_TEXTUREFORMAT_R8_UINT;
    tex_info.usage                = SDL_GPU_TEXTUREUSAGE_SAMPLER;
    tex_info.width                = (Uint32)w;
    tex_info.height               = (Uint32)h;
    tex_info.layer_count_or_depth = 1;
    tex_info.num_levels           = 1;
    tex_info.sample_count         = SDL_GPU_SAMPLECOUNT_1;
    gpu_fb_tex         = SDL_CreateGPUTexture(gpu_device, &tex_info);
    gpu_palette_id_tex = SDL_CreateGPUTexture(gpu_device, &tex_info);

    SDL_GPUTransferBufferCreateInfo xfer_info = {0};
    xfer_info.usage = SDL_GPU_TRANSFERBUFFERUSAGE_UPLOAD;
    xfer_info.size  = (Uint32)(w * h * 2);   // fb + palette_id back-to-back
    gpu_frame_xfer = SDL_CreateGPUTransferBuffer(gpu_device, &xfer_info);

    gpu_fb_tex_w = w;
    gpu_fb_tex_h = h;
}

// Offscreen colour target the editor's Viewport panel samples. Same format as
// the swapchain so the palette pipeline (built for gpu_swapchain_format) can
// render into it; COLOR_TARGET so it's a render target, SAMPLER so ImGui can
// Image() it.
static void gpu_ensure_scene_tex(int w, int h) {
    if (gpu_scene_tex && w == gpu_scene_w && h == gpu_scene_h) return;
    if (gpu_scene_tex) SDL_ReleaseGPUTexture(gpu_device, gpu_scene_tex);
    SDL_GPUTextureCreateInfo ti = {0};
    ti.type                 = SDL_GPU_TEXTURETYPE_2D;
    ti.format               = gpu_swapchain_format;
    ti.usage                = SDL_GPU_TEXTUREUSAGE_COLOR_TARGET | SDL_GPU_TEXTUREUSAGE_SAMPLER;
    ti.width                = (Uint32)w;
    ti.height               = (Uint32)h;
    ti.layer_count_or_depth = 1;
    ti.num_levels           = 1;
    ti.sample_count         = SDL_GPU_SAMPLECOUNT_1;
    gpu_scene_tex = SDL_CreateGPUTexture(gpu_device, &ti);
    gpu_scene_w = w;
    gpu_scene_h = h;
}

// ImTextureID for the editor Viewport panel (NULL when not yet rendered).
void *VID_EditorSceneTexture(void) { return (void *)gpu_scene_tex; }

static int gpu_init(SDL_Window *win) {
    SDL_GPUShaderFormat fmts = SDL_GPU_SHADERFORMAT_SPIRV | SDL_GPU_SHADERFORMAT_MSL;
    gpu_device = SDL_CreateGPUDevice(fmts, false, NULL);
    if (!gpu_device) {
        Sys_Error("SDL_CreateGPUDevice failed: %s", SDL_GetError());
        return 0;
    }
    if (!SDL_ClaimWindowForGPUDevice(gpu_device, win)) {
        Sys_Error("SDL_ClaimWindowForGPUDevice failed: %s", SDL_GetError());
        return 0;
    }
    gpu_swapchain_format = SDL_GetGPUSwapchainTextureFormat(gpu_device, win);

    SDL_GPUShaderFormat active = SDL_GetGPUShaderFormats(gpu_device);

    SDL_GPUShaderCreateInfo vs_info = {0};
    SDL_GPUShaderCreateInfo fs_info = {0};
    vs_info.stage = SDL_GPU_SHADERSTAGE_VERTEX;
    fs_info.stage = SDL_GPU_SHADERSTAGE_FRAGMENT;
    fs_info.num_samplers         = 3;
    fs_info.num_uniform_buffers  = 1;   // scanline params

    if (active & SDL_GPU_SHADERFORMAT_MSL) {
        vs_info.code        = (const Uint8 *)palette_vert_msl;
        vs_info.code_size   = strlen(palette_vert_msl);
        vs_info.entrypoint  = "main0";
        vs_info.format      = SDL_GPU_SHADERFORMAT_MSL;
        fs_info.code        = (const Uint8 *)palette_frag_msl;
        fs_info.code_size   = strlen(palette_frag_msl);
        fs_info.entrypoint  = "main0";
        fs_info.format      = SDL_GPU_SHADERFORMAT_MSL;
    } else {
        vs_info.code        = palette_vert_spv;
        vs_info.code_size   = palette_vert_spv_size;
        vs_info.entrypoint  = "main";
        vs_info.format      = SDL_GPU_SHADERFORMAT_SPIRV;
        fs_info.code        = palette_frag_spv;
        fs_info.code_size   = palette_frag_spv_size;
        fs_info.entrypoint  = "main";
        fs_info.format      = SDL_GPU_SHADERFORMAT_SPIRV;
    }
    SDL_GPUShader *vs = SDL_CreateGPUShader(gpu_device, &vs_info);
    SDL_GPUShader *fs = SDL_CreateGPUShader(gpu_device, &fs_info);
    if (!vs || !fs) {
        Sys_Error("SDL_CreateGPUShader failed: %s", SDL_GetError());
        return 0;
    }

    SDL_GPUColorTargetDescription color_target = {0};
    color_target.format = gpu_swapchain_format;
    SDL_GPUGraphicsPipelineCreateInfo pipe_info = {0};
    pipe_info.vertex_shader   = vs;
    pipe_info.fragment_shader = fs;
    pipe_info.primitive_type  = SDL_GPU_PRIMITIVETYPE_TRIANGLELIST;
    pipe_info.rasterizer_state.fill_mode   = SDL_GPU_FILLMODE_FILL;
    pipe_info.rasterizer_state.cull_mode   = SDL_GPU_CULLMODE_NONE;
    pipe_info.rasterizer_state.front_face  = SDL_GPU_FRONTFACE_COUNTER_CLOCKWISE;
    pipe_info.multisample_state.sample_count = SDL_GPU_SAMPLECOUNT_1;
    pipe_info.target_info.num_color_targets  = 1;
    pipe_info.target_info.color_target_descriptions = &color_target;
    gpu_pipeline = SDL_CreateGPUGraphicsPipeline(gpu_device, &pipe_info);
    SDL_ReleaseGPUShader(gpu_device, vs);
    SDL_ReleaseGPUShader(gpu_device, fs);
    if (!gpu_pipeline) {
        Sys_Error("SDL_CreateGPUGraphicsPipeline failed: %s", SDL_GetError());
        return 0;
    }

    // Second pipeline: crop-screenshot overlay (rect_overlay shaders) with
    // standard alpha blending so the fragment shader can dim, discard, or
    // draw white border pixels by tweaking output alpha.
    SDL_GPUShaderCreateInfo rvs_info = {0};
    SDL_GPUShaderCreateInfo rfs_info = {0};
    rvs_info.stage = SDL_GPU_SHADERSTAGE_VERTEX;
    rfs_info.stage = SDL_GPU_SHADERSTAGE_FRAGMENT;
    rfs_info.num_uniform_buffers = 1;
    if (active & SDL_GPU_SHADERFORMAT_MSL) {
        rvs_info.code = (const Uint8 *)rect_overlay_vert_msl;
        rvs_info.code_size = strlen(rect_overlay_vert_msl);
        rvs_info.entrypoint = "main0";
        rvs_info.format = SDL_GPU_SHADERFORMAT_MSL;
        rfs_info.code = (const Uint8 *)rect_overlay_frag_msl;
        rfs_info.code_size = strlen(rect_overlay_frag_msl);
        rfs_info.entrypoint = "main0";
        rfs_info.format = SDL_GPU_SHADERFORMAT_MSL;
    } else {
        rvs_info.code = rect_overlay_vert_spv;
        rvs_info.code_size = rect_overlay_vert_spv_size;
        rvs_info.entrypoint = "main";
        rvs_info.format = SDL_GPU_SHADERFORMAT_SPIRV;
        rfs_info.code = rect_overlay_frag_spv;
        rfs_info.code_size = rect_overlay_frag_spv_size;
        rfs_info.entrypoint = "main";
        rfs_info.format = SDL_GPU_SHADERFORMAT_SPIRV;
    }
    SDL_GPUShader *rvs = SDL_CreateGPUShader(gpu_device, &rvs_info);
    SDL_GPUShader *rfs = SDL_CreateGPUShader(gpu_device, &rfs_info);
    if (!rvs || !rfs) {
        Sys_Error("SDL_CreateGPUShader (rect_overlay) failed: %s", SDL_GetError());
        return 0;
    }
    SDL_GPUColorTargetDescription rect_target = {0};
    rect_target.format = gpu_swapchain_format;
    rect_target.blend_state.enable_blend          = true;
    rect_target.blend_state.src_color_blendfactor = SDL_GPU_BLENDFACTOR_SRC_ALPHA;
    rect_target.blend_state.dst_color_blendfactor = SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
    rect_target.blend_state.color_blend_op        = SDL_GPU_BLENDOP_ADD;
    rect_target.blend_state.src_alpha_blendfactor = SDL_GPU_BLENDFACTOR_ONE;
    rect_target.blend_state.dst_alpha_blendfactor = SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
    rect_target.blend_state.alpha_blend_op        = SDL_GPU_BLENDOP_ADD;
    SDL_GPUGraphicsPipelineCreateInfo rpipe_info = {0};
    rpipe_info.vertex_shader   = rvs;
    rpipe_info.fragment_shader = rfs;
    rpipe_info.primitive_type  = SDL_GPU_PRIMITIVETYPE_TRIANGLELIST;
    rpipe_info.rasterizer_state.fill_mode  = SDL_GPU_FILLMODE_FILL;
    rpipe_info.rasterizer_state.cull_mode  = SDL_GPU_CULLMODE_NONE;
    rpipe_info.rasterizer_state.front_face = SDL_GPU_FRONTFACE_COUNTER_CLOCKWISE;
    rpipe_info.multisample_state.sample_count = SDL_GPU_SAMPLECOUNT_1;
    rpipe_info.target_info.num_color_targets  = 1;
    rpipe_info.target_info.color_target_descriptions = &rect_target;
    gpu_rect_pipeline = SDL_CreateGPUGraphicsPipeline(gpu_device, &rpipe_info);
    SDL_ReleaseGPUShader(gpu_device, rvs);
    SDL_ReleaseGPUShader(gpu_device, rfs);
    if (!gpu_rect_pipeline) {
        Sys_Error("SDL_CreateGPUGraphicsPipeline (rect_overlay) failed: %s",
                  SDL_GetError());
        return 0;
    }

    SDL_GPUSamplerCreateInfo samp_info = {0};
    samp_info.min_filter     = SDL_GPU_FILTER_NEAREST;
    samp_info.mag_filter     = SDL_GPU_FILTER_NEAREST;
    samp_info.mipmap_mode    = SDL_GPU_SAMPLERMIPMAPMODE_NEAREST;
    samp_info.address_mode_u = SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE;
    samp_info.address_mode_v = SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE;
    samp_info.address_mode_w = SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE;
    gpu_sampler = SDL_CreateGPUSampler(gpu_device, &samp_info);

    SDL_GPUTextureCreateInfo pal_info = {0};
    pal_info.type                 = SDL_GPU_TEXTURETYPE_2D;
    pal_info.format               = SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM;
    pal_info.usage                = SDL_GPU_TEXTUREUSAGE_SAMPLER;
    pal_info.width                = 256;
    pal_info.height               = VID_NUM_PALETTES;
    pal_info.layer_count_or_depth = 1;
    pal_info.num_levels           = 1;
    pal_info.sample_count         = SDL_GPU_SAMPLECOUNT_1;
    gpu_palette_tex = SDL_CreateGPUTexture(gpu_device, &pal_info);

    SDL_GPUTransferBufferCreateInfo pal_xfer_info = {0};
    pal_xfer_info.usage = SDL_GPU_TRANSFERBUFFERUSAGE_UPLOAD;
    pal_xfer_info.size  = 256 * VID_NUM_PALETTES * 4;
    gpu_palette_xfer = SDL_CreateGPUTransferBuffer(gpu_device, &pal_xfer_info);

    gpu_create_frame_textures(vid_super_w, vid_super_h);
    return 1;
}

static void gpu_shutdown(void) {
    if (!gpu_device) return;
    if (gpu_pipeline)       SDL_ReleaseGPUGraphicsPipeline(gpu_device, gpu_pipeline);
    if (gpu_rect_pipeline)  SDL_ReleaseGPUGraphicsPipeline(gpu_device, gpu_rect_pipeline);
    if (gpu_sampler)        SDL_ReleaseGPUSampler         (gpu_device, gpu_sampler);
    if (gpu_fb_tex)         SDL_ReleaseGPUTexture         (gpu_device, gpu_fb_tex);
    if (gpu_palette_id_tex) SDL_ReleaseGPUTexture         (gpu_device, gpu_palette_id_tex);
    if (gpu_palette_tex)    SDL_ReleaseGPUTexture         (gpu_device, gpu_palette_tex);
    if (gpu_frame_xfer)     SDL_ReleaseGPUTransferBuffer  (gpu_device, gpu_frame_xfer);
    if (gpu_palette_xfer)   SDL_ReleaseGPUTransferBuffer  (gpu_device, gpu_palette_xfer);
    SDL_ReleaseWindowFromGPUDevice(gpu_device, sdl_window);
    SDL_DestroyGPUDevice(gpu_device);
    gpu_device = NULL; gpu_pipeline = NULL; gpu_rect_pipeline = NULL;
    gpu_sampler = NULL;
    gpu_fb_tex = NULL; gpu_palette_id_tex = NULL; gpu_palette_tex = NULL;
    gpu_frame_xfer = NULL; gpu_palette_xfer = NULL;
}

// Forward decls — implemented in imgui_layer.c via imgui_bridge.cpp.
extern void ImguiLayer_PrepareGPU(SDL_GPUCommandBuffer *cmd);
extern void ImguiLayer_RenderGPU (SDL_GPUCommandBuffer *cmd, SDL_GPURenderPass *pass);
extern int Editor_IsOpen(void);
extern int ImguiLayer_IsOpen(void);

static void gpu_render_frame(void) {
    // GPU texture is sized to the *super* buffer dims (the actual extent the
    // software renderer fills). With ss=1 these equal vid_render_w/h; with
    // ss>1 they are larger and palette.frag.glsl averages each ss×ss block of
    // expanded texels down to the render grid (true SSAA — the sampler is
    // NEAREST and the R8_UINT index texture can't be hardware-filtered).
    int tex_w = vid_super_w;
    int tex_h = vid_super_h;
    if (tex_w != gpu_fb_tex_w || tex_h != gpu_fb_tex_h)
        gpu_create_frame_textures(tex_w, tex_h);

    SDL_GPUCommandBuffer *cmd = SDL_AcquireGPUCommandBuffer(gpu_device);
    if (!cmd) return;

    gpu_upload_palette(cmd);

    Perf_PushScope("gpu_upload");
    void *mapped = SDL_MapGPUTransferBuffer(gpu_device, gpu_frame_xfer, true);
    if (mapped) {
        uint8_t *dst = (uint8_t *)mapped;
        int src_stride = (int)vid.rowbytes;   // = vid_super_w
        for (int y = 0; y < tex_h; y++)
            memcpy(dst + y * tex_w, vid.buffer + y * src_stride, tex_w);
        uint8_t *dst_pid = dst + tex_w * tex_h;
        for (int y = 0; y < tex_h; y++)
            memcpy(dst_pid + y * tex_w, vid_palette_id + y * src_stride, tex_w);
        SDL_UnmapGPUTransferBuffer(gpu_device, gpu_frame_xfer);
    }
    SDL_GPUCopyPass *copy = SDL_BeginGPUCopyPass(cmd);
    {
        SDL_GPUTextureTransferInfo src = {0};
        src.transfer_buffer = gpu_frame_xfer;
        src.pixels_per_row  = (Uint32)tex_w;
        src.rows_per_layer  = (Uint32)tex_h;
        SDL_GPUTextureRegion dst = {0};
        dst.texture = gpu_fb_tex;
        dst.w = (Uint32)tex_w; dst.h = (Uint32)tex_h; dst.d = 1;
        SDL_UploadToGPUTexture(copy, &src, &dst, true);
    }
    {
        SDL_GPUTextureTransferInfo src = {0};
        src.transfer_buffer = gpu_frame_xfer;
        src.offset          = (Uint32)(tex_w * tex_h);
        src.pixels_per_row  = (Uint32)tex_w;
        src.rows_per_layer  = (Uint32)tex_h;
        SDL_GPUTextureRegion dst = {0};
        dst.texture = gpu_palette_id_tex;
        dst.w = (Uint32)tex_w; dst.h = (Uint32)tex_h; dst.d = 1;
        SDL_UploadToGPUTexture(copy, &src, &dst, true);
    }
    SDL_EndGPUCopyPass(copy);
    Perf_PopScope();

    // Scene goes into the editor's Viewport panel whenever the docked overlay
    // is up — the in-game editor OR the F3 dev overlay.
    int scene_in_panel = Editor_IsOpen() || ImguiLayer_IsOpen();
    if (scene_in_panel) {
        gpu_ensure_scene_tex(vid_render_w, vid_render_h);
        SDL_GPUColorTargetInfo sct = {0};
        sct.texture  = gpu_scene_tex;
        sct.load_op  = SDL_GPU_LOADOP_CLEAR;
        sct.store_op = SDL_GPU_STOREOP_STORE;
        sct.clear_color.a = 1.0f;
        SDL_GPURenderPass *spass = SDL_BeginGPURenderPass(cmd, &sct, 1, NULL);
        SDL_BindGPUGraphicsPipeline(spass, gpu_pipeline);
        SDL_GPUViewport svp = {0};
        svp.w = (float)vid_render_w; svp.h = (float)vid_render_h; svp.max_depth = 1.0f;
        SDL_SetGPUViewport(spass, &svp);
        SDL_GPUTextureSamplerBinding sb[3];
        sb[0].texture = gpu_fb_tex;         sb[0].sampler = gpu_sampler;
        sb[1].texture = gpu_palette_id_tex; sb[1].sampler = gpu_sampler;
        sb[2].texture = gpu_palette_tex;    sb[2].sampler = gpu_sampler;
        SDL_BindGPUFragmentSamplers(spass, 0, sb, 3);
        struct { float intensity, size, supersample, pad1; } sp =
            { 0.0f, 1.0f, (float)vid_supersample_active, 0.0f };   // no scanlines in the editor
        SDL_PushGPUFragmentUniformData(cmd, 0, &sp, sizeof(sp));
        SDL_DrawGPUPrimitives(spass, 3, 1, 0, 0);
        SDL_EndGPURenderPass(spass);
    }

    ImguiLayer_PrepareGPU(cmd);

    Perf_PushScope("gpu_present");
    SDL_GPUTexture *swap_tex = NULL;
    Uint32 swap_w = 0, swap_h = 0;
    if (!SDL_WaitAndAcquireGPUSwapchainTexture(cmd, sdl_window, &swap_tex, &swap_w, &swap_h)
        || !swap_tex)
    {
        SDL_SubmitGPUCommandBuffer(cmd);
        Perf_PopScope();
        return;
    }
    {
        static int diag_printed = 0;
        if (!diag_printed) {
            diag_printed = 1;
            int win_w = 0, win_h = 0;
            SDL_GetWindowSize(sdl_window, &win_w, &win_h);
            int px_w = 0, px_h = 0;
            SDL_GetWindowSizeInPixels(sdl_window, &px_w, &px_h);
            Con_Printf("vid: render=%dx%d super=%dx%d ss=%d vid.w=%u vid.h=%u rowbytes=%u\n",
                       vid_render_w, vid_render_h, vid_super_w, vid_super_h,
                       vid_supersample_active, vid.width, vid.height, vid.rowbytes);
            Con_Printf("vid: swap=%ux%u win=%dx%d px=%dx%d\n",
                       swap_w, swap_h, win_w, win_h, px_w, px_h);
        }
    }

    SDL_GPUColorTargetInfo color_target = {0};
    color_target.texture = swap_tex;
    color_target.load_op = SDL_GPU_LOADOP_CLEAR;
    color_target.store_op = SDL_GPU_STOREOP_STORE;
    // clear_color default-zeroes to opaque-black, which is what we want.
    color_target.clear_color.a = 1.0f;
    SDL_GPURenderPass *pass = SDL_BeginGPURenderPass(cmd, &color_target, 1, NULL);

    if (!scene_in_panel) {
        SDL_BindGPUGraphicsPipeline(pass, gpu_pipeline);

        // Integer-scale aspect-preserving letterbox. Matches the prior
        // SDL_RenderLogicalPresentation INTEGER_SCALE behaviour.
        int int_scale = (int)(swap_w / (Uint32)vid_render_w);
        int sy        = (int)(swap_h / (Uint32)vid_render_h);
        if (sy < int_scale) int_scale = sy;
        if (int_scale < 1)  int_scale = 1;
        int vp_w = vid_render_w * int_scale;
        int vp_h = vid_render_h * int_scale;
        SDL_GPUViewport vp = {0};
        vp.x = (float)(((int)swap_w - vp_w) / 2);
        vp.y = (float)(((int)swap_h - vp_h) / 2);
        vp.w = (float)vp_w;
        vp.h = (float)vp_h;
        vp.max_depth = 1.0f;
        SDL_SetGPUViewport(pass, &vp);

        SDL_GPUTextureSamplerBinding bindings[3];
        bindings[0].texture = gpu_fb_tex;         bindings[0].sampler = gpu_sampler;
        bindings[1].texture = gpu_palette_id_tex; bindings[1].sampler = gpu_sampler;
        bindings[2].texture = gpu_palette_tex;    bindings[2].sampler = gpu_sampler;
        SDL_BindGPUFragmentSamplers(pass, 0, bindings, 3);

        // Fragment params: scanline overlay + supersample factor. Layout matches
        // the std140 UBO in palette.frag.glsl (four floats = 16 bytes). The shader
        // averages each ss×ss block of expanded texels down to one render texel, so
        // it needs the live ss to know the block size (ss=1 → single fetch).
        struct { float intensity, size, supersample, pad1; } scan_params;
        float intensity = vid_scanline_intensity.value;
        float size      = vid_scanline_size.value;
        if (vid_scanlines.value == 0.0f) intensity = 0.0f;
        if (intensity < 0.0f) intensity = 0.0f;
        if (intensity > 1.0f) intensity = 1.0f;
        if (size < 1.0f) size = 1.0f;
        if (size > 8.0f) size = 8.0f;
        scan_params.intensity   = intensity;
        scan_params.size        = size;
        scan_params.supersample = (float)vid_supersample_active;
        scan_params.pad1        = 0.0f;
        SDL_PushGPUFragmentUniformData(cmd, 0, &scan_params, sizeof(scan_params));

        SDL_DrawGPUPrimitives(pass, 3, 1, 0, 0);

        // Crop-screenshot selection overlay: draws after the palette pass and
        // before ImGui, so it overlays the framebuffer but the dev overlay still
        // sits on top.
        if (Crop_Active()) {
            int x0 = 0, y0 = 0, x1 = 0, y1 = 0;
            Crop_GetRect(&x0, &y0, &x1, &y1);
            // Rect is in super-pixel space; map super → viewport-local swapchain
            // pixels. The palette pass already scaled (vid_super_w × vid_super_h)
            // into (vp_w × vp_h), so use that ratio.
            float sx = (float)vp_w / (float)vid_super_w;
            float sy = (float)vp_h / (float)vid_super_h;
            struct {
                float rect[4];      // x0, y0, x1_excl, y1_excl
                float viewport[4];  // origin_x, origin_y, w, h (swap-pixels)
                float border_w;
                float dim_alpha;
                float pad0, pad1;
            } rp;
            rp.rect[0] = (float)x0       * sx;
            rp.rect[1] = (float)y0       * sy;
            rp.rect[2] = (float)(x1 + 1) * sx;
            rp.rect[3] = (float)(y1 + 1) * sy;
            rp.viewport[0] = vp.x;
            rp.viewport[1] = vp.y;
            rp.viewport[2] = vp.w;
            rp.viewport[3] = vp.h;
            rp.border_w  = (float)int_scale;  // one logical pixel
            rp.dim_alpha = 0.5f;
            rp.pad0 = rp.pad1 = 0.0f;
            SDL_BindGPUGraphicsPipeline(pass, gpu_rect_pipeline);
            SDL_PushGPUFragmentUniformData(cmd, 0, &rp, sizeof(rp));
            SDL_DrawGPUPrimitives(pass, 3, 1, 0, 0);
        }
    }

    ImguiLayer_RenderGPU(cmd, pass);

    SDL_EndGPURenderPass(pass);

    // Optional GPU screenshot: schedule a download from the swapchain texture
    // before submit, so the fence we acquire is post-rasterise. Then map the
    // readback transfer buffer and encode PNG.
    int do_shot = gpu_screenshot_pending;
    if (do_shot) {
        int rb_bytes = (int)swap_w * (int)swap_h * 4;
        if (!gpu_readback_xfer || gpu_readback_size < rb_bytes) {
            if (gpu_readback_xfer) SDL_ReleaseGPUTransferBuffer(gpu_device, gpu_readback_xfer);
            SDL_GPUTransferBufferCreateInfo rb_info = {0};
            rb_info.usage = SDL_GPU_TRANSFERBUFFERUSAGE_DOWNLOAD;
            rb_info.size  = (Uint32)rb_bytes;
            gpu_readback_xfer = SDL_CreateGPUTransferBuffer(gpu_device, &rb_info);
            gpu_readback_size = rb_bytes;
        }
        if (gpu_readback_xfer) {
            SDL_GPUCopyPass *cp = SDL_BeginGPUCopyPass(cmd);
            SDL_GPUTextureRegion src = {0};
            src.texture = swap_tex;
            src.w = swap_w; src.h = swap_h; src.d = 1;
            SDL_GPUTextureTransferInfo dst = {0};
            dst.transfer_buffer = gpu_readback_xfer;
            dst.pixels_per_row  = swap_w;
            dst.rows_per_layer  = swap_h;
            SDL_DownloadFromGPUTexture(cp, &src, &dst);
            SDL_EndGPUCopyPass(cp);
        }
    }

    if (do_shot && gpu_readback_xfer) {
        SDL_GPUFence *fence = SDL_SubmitGPUCommandBufferAndAcquireFence(cmd);
        if (fence) {
            SDL_WaitForGPUFences(gpu_device, true, &fence, 1);
            void *mapped = SDL_MapGPUTransferBuffer(gpu_device, gpu_readback_xfer, false);
            if (mapped) {
                // Swapchain on macOS is B8G8R8A8_UNORM; swizzle to RGB for PNG.
                // (Other backends may use different orders — extend if needed.)
                int W = (int)swap_w, H = (int)swap_h;
                unsigned char *rgb = (unsigned char *)malloc((size_t)W * H * 3);
                if (rgb) {
                    const uint8_t *src = (const uint8_t *)mapped;
                    for (int i = 0; i < W * H; i++) {
                        rgb[i*3 + 0] = src[i*4 + 2]; // R from B-position
                        rgb[i*3 + 1] = src[i*4 + 1]; // G
                        rgb[i*3 + 2] = src[i*4 + 0]; // B from R-position
                    }
                    stbi_write_png(gpu_screenshot_path, W, H, 3, rgb, W * 3);
                    free(rgb);
                }
                SDL_UnmapGPUTransferBuffer(gpu_device, gpu_readback_xfer);
            }
            SDL_ReleaseGPUFence(gpu_device, fence);
        }
        gpu_screenshot_pending = 0;
    } else {
        SDL_SubmitGPUCommandBuffer(cmd);
    }
    Perf_PopScope();
}

// Request a GPU-side screenshot. Returns 1 if the request was queued (i.e.
// no other screenshot is pending). The next gpu_render_frame downloads the
// swapchain texture and writes a PNG to `path`. Caller-supplied path must be
// short enough to fit in gpu_screenshot_path (~500 bytes).
int VID_RequestGPUScreenshot(const char *path) {
    if (!gpu_device)        return 0;
    if (gpu_screenshot_pending) return 0;
    if (!path || !path[0])  return 0;
    snprintf(gpu_screenshot_path, sizeof(gpu_screenshot_path), "%s", path);
    gpu_screenshot_pending = 1;
    return 1;
}
int VID_GPUScreenshotPending(void) { return gpu_screenshot_pending; }

static void VID_ApplyResolution(int render_scale, int ss)
{
    extern short *d_pzbuffer;
    extern int    D_SurfaceCacheForRes(int w, int h);
    extern void   D_InitCaches(void *buffer, int size);

    if (render_scale < 1) render_scale = 1;
    if (render_scale > 4) render_scale = 4;
    if (ss < 1) ss = 1;
    if (ss > 4) ss = 4;
    while (render_scale * ss > 8 && ss > 1) ss--;

    int render_w = VID_WIDTH  * render_scale;
    int render_h = VID_HEIGHT * render_scale;
    int super_w  = render_w * ss;
    int super_h  = render_h * ss;

    if (gpu_device) {
        gpu_create_frame_textures(render_w, render_h);
    }

    vid_render_w = render_w;
    vid_render_h = render_h;
    vid_super_w  = super_w;
    vid_super_h  = super_h;
    vid_scale_active       = render_scale;
    vid_supersample_active = ss;

    vid.width         = super_w;
    vid.height        = super_h;
    vid.rowbytes      = super_w;
    vid.conwidth      = super_w;
    vid.conheight     = super_h;
    vid.conrowbytes   = super_w;
    vid.maxwarpwidth  = WARP_WIDTH;
    vid.maxwarpheight = WARP_HEIGHT;
    vid.recalc_refdef = 1;

    {
        extern void D_FlushCaches(void);
        D_FlushCaches();
    }
    int zbuf_bytes  = super_w * super_h * sizeof(short);
    int cache_bytes = D_SurfaceCacheForRes(super_w, super_h);
    D_InitCaches((byte *)d_pzbuffer + zbuf_bytes, cache_bytes);
}

static void VID_ApplyWindowScale(int scale)
{
    SDL_SetWindowSize(sdl_window, VID_WIDTH * scale, VID_HEIGHT * scale);
}

// Capture the current SDL window position AND size into the archived cvars
// so the next launch can restore it. Invoked from the Video Options menu —
// no autosave, so casual dragging won't quietly overwrite saved values.
static void VID_SaveWindow(void)
{
    int x = 0, y = 0, w = 0, h = 0;
    if (!sdl_window) return;
    SDL_GetWindowPosition(sdl_window, &x, &y);
    SDL_GetWindowSize(sdl_window, &w, &h);
    Cvar_SetValue("vid_window_x", (float)x);
    Cvar_SetValue("vid_window_y", (float)y);
    Cvar_SetValue("vid_window_w", (float)w);
    Cvar_SetValue("vid_window_h", (float)h);
}

// ---------------------------------------------------------------------------
// Video Options menu
// ---------------------------------------------------------------------------

static const float vid_sl_intensity_buckets[4] = { 0.25f, 0.50f, 0.75f, 1.00f };
static const char *vid_sl_intensity_labels[4]  = { "25%", "50%", "75%", "100%" };

static int vid_sl_intensity_bucket(void)
{
    float v = vid_scanline_intensity.value;
    int   best_i = 1;       // default bucket for 0.5
    float best_d = 1e9f;
    for (int i = 0; i < 4; i++) {
        float d = v - vid_sl_intensity_buckets[i];
        if (d < 0) d = -d;
        if (d < best_d) { best_d = d; best_i = i; }
    }
    return best_i;
}

static int vid_sl_size_index(void)
{
    int s = (int)vid_scanline_size.value;
    if (s < 1) s = 1;
    if (s > 3) s = 3;
    return s - 1;  // 0-based index for cycling
}

static void VID_MenuDraw(void)
{
    qpic_t *p = Draw_CachePic("gfx/vidmodes.lmp");
    M_DrawPic((320 - p->width) / 2, 4, p);

    M_Print(64, 30, "Supersample");
    int ss_y = 42;
    for (int i = 0; i < VID_NUM_SCALES; i++)
    {
        if (vid_scale_factors[i] == vid_supersample_active)
            M_PrintWhite(80, ss_y + i * 8, (char *)vid_ss_labels[i]);
        else
            M_Print(80, ss_y + i * 8, (char *)vid_ss_labels[i]);
        if (vid_menu_cursor == VID_MENU_SS_BASE + i)
            M_DrawCharacter(72, ss_y + i * 8, 12 + ((int)(realtime * 4) & 1));
    }

    M_Print(64, 78, "Render Resolution");
    int render_y = 90;
    for (int i = 0; i < VID_NUM_SCALES; i++)
    {
        if (vid_scale_factors[i] == vid_scale_active)
            M_PrintWhite(80, render_y + i * 8, (char *)vid_scale_labels[i]);
        else
            M_Print(80, render_y + i * 8, (char *)vid_scale_labels[i]);
        if (vid_menu_cursor == VID_MENU_RENDER_BASE + i)
            M_DrawCharacter(72, render_y + i * 8, 12 + ((int)(realtime * 4) & 1));
    }

    M_Print(64, 126, "Window Size");
    int window_y = 138;
    for (int i = 0; i < VID_NUM_SCALES; i++)
    {
        if (vid_scale_factors[i] == vid_window_scale_active)
            M_PrintWhite(80, window_y + i * 8, (char *)vid_scale_labels[i]);
        else
            M_Print(80, window_y + i * 8, (char *)vid_scale_labels[i]);
        if (vid_menu_cursor == VID_MENU_WINDOW_BASE + i)
            M_DrawCharacter(72, window_y + i * 8, 12 + ((int)(realtime * 4) & 1));
    }

    // Compact scanline section — three single-line stepper rows.
    int sl_y = 170;

    M_Print(64, sl_y, "Scanlines");
    M_Print(160, sl_y, vid_scanlines.value != 0.0f ? "On" : "Off");
    if (vid_menu_cursor == VID_MENU_SCANLINES_POS)
        M_DrawCharacter(56, sl_y, 12 + ((int)(realtime * 4) & 1));

    M_Print(64, sl_y + 8, "Intensity");
    M_Print(160, sl_y + 8, (char *)vid_sl_intensity_labels[vid_sl_intensity_bucket()]);
    if (vid_menu_cursor == VID_MENU_SL_INTENSITY_POS)
        M_DrawCharacter(56, sl_y + 8, 12 + ((int)(realtime * 4) & 1));

    M_Print(64, sl_y + 16, "Size");
    {
        char sz[8];
        snprintf(sz, sizeof sz, "%dpx", vid_sl_size_index() + 1);
        M_Print(160, sl_y + 16, sz);
    }
    if (vid_menu_cursor == VID_MENU_SL_SIZE_POS)
        M_DrawCharacter(56, sl_y + 16, 12 + ((int)(realtime * 4) & 1));

    int save_y = sl_y + 24;
    M_Print(80, save_y, "Save Window Pos & Size");
    if (vid_menu_cursor == VID_MENU_SAVE_POS)
        M_DrawCharacter(72, save_y, 12 + ((int)(realtime * 4) & 1));
}

static void VID_MenuKey(int key)
{
    switch (key)
    {
    case K_ESCAPE:
        M_Menu_Options_f();
        break;

    case K_UPARROW:
        S_LocalSound("misc/menu1.wav");
        vid_menu_cursor = (vid_menu_cursor - 1 + VID_MENU_ITEMS) % VID_MENU_ITEMS;
        break;

    case K_DOWNARROW:
        S_LocalSound("misc/menu1.wav");
        vid_menu_cursor = (vid_menu_cursor + 1) % VID_MENU_ITEMS;
        break;

    case K_LEFTARROW:
    case K_RIGHTARROW:
    {
        int dir = (key == K_RIGHTARROW) ? +1 : -1;
        if (vid_menu_cursor == VID_MENU_SCANLINES_POS) {
            float nv = (vid_scanlines.value != 0.0f) ? 0.0f : 1.0f;
            Cvar_SetValue("vid_scanlines", nv);
            S_LocalSound("misc/menu3.wav");
        } else if (vid_menu_cursor == VID_MENU_SL_INTENSITY_POS) {
            int b = vid_sl_intensity_bucket();
            b = (b + dir + 4) % 4;
            Cvar_SetValue("vid_scanline_intensity", vid_sl_intensity_buckets[b]);
            S_LocalSound("misc/menu3.wav");
        } else if (vid_menu_cursor == VID_MENU_SL_SIZE_POS) {
            int s = vid_sl_size_index();
            s = (s + dir + 3) % 3;
            Cvar_SetValue("vid_scanline_size", (float)(s + 1));
            S_LocalSound("misc/menu3.wav");
        }
        break;
    }

    case K_ENTER:
    case K_SPACE:
        if (vid_menu_cursor < VID_MENU_RENDER_BASE)
        {
            // Supersample row.
            int new_ss = vid_scale_factors[vid_menu_cursor - VID_MENU_SS_BASE];
            Cvar_SetValue("vid_supersample", (float)new_ss);
            VID_ApplyResolution(vid_scale_active, new_ss);
        }
        else if (vid_menu_cursor < VID_MENU_WINDOW_BASE)
        {
            // Render-resolution row.
            int new_scale = vid_scale_factors[vid_menu_cursor - VID_MENU_RENDER_BASE];
            Cvar_SetValue("vid_scale", (float)new_scale);
            VID_ApplyResolution(new_scale, vid_supersample_active);
        }
        else if (vid_menu_cursor < VID_MENU_WINDOW_BASE + VID_NUM_SCALES)
        {
            // Window-size row.
            int new_scale = vid_scale_factors[vid_menu_cursor - VID_MENU_WINDOW_BASE];
            vid_window_scale_active = new_scale;
            Cvar_SetValue("vid_window_scale", (float)new_scale);
            VID_ApplyWindowScale(new_scale);
        }
        else if (vid_menu_cursor == VID_MENU_SAVE_POS)
        {
            VID_SaveWindow();
        }
        else
        {
            // Scanline rows: Enter mirrors right-arrow (cycle forward).
            int dir = +1;
            if (vid_menu_cursor == VID_MENU_SCANLINES_POS) {
                float nv = (vid_scanlines.value != 0.0f) ? 0.0f : 1.0f;
                Cvar_SetValue("vid_scanlines", nv);
            } else if (vid_menu_cursor == VID_MENU_SL_INTENSITY_POS) {
                int b = (vid_sl_intensity_bucket() + dir + 4) % 4;
                Cvar_SetValue("vid_scanline_intensity", vid_sl_intensity_buckets[b]);
            } else if (vid_menu_cursor == VID_MENU_SL_SIZE_POS) {
                int s = (vid_sl_size_index() + dir + 3) % 3;
                Cvar_SetValue("vid_scanline_size", (float)(s + 1));
            }
        }
        S_LocalSound("misc/menu2.wav");
        break;

    default:
        break;
    }
}

// ---------------------------------------------------------------------------
// Init / shutdown
// ---------------------------------------------------------------------------

extern qboolean sys_headless;
extern qboolean sys_nofocus;

// Pre-load the video cvars we need at window-creation time. The engine
// doesn't exec config.cfg until after VID_Init returns (via deferred
// Cbuf_Execute in the first _Host_Frame), so without this the cvars still
// hold their registration defaults when we call SDL_CreateWindow.
static void vid_preload_cvars_from_config(void)
{
    extern char com_gamedir[MAX_OSPATH];
    char path[MAX_OSPATH + 16];
    FILE *f;
    char line[256];

    snprintf(path, sizeof path, "%s/config.cfg", com_gamedir);
    f = fopen(path, "r");
    if (!f) return;

    while (fgets(line, sizeof line, f))
    {
        float v;
        if      (sscanf(line, "vid_window_scale \"%f", &v) == 1) Cvar_SetValue("vid_window_scale", v);
        else if (sscanf(line, "vid_window_x \"%f", &v) == 1)     Cvar_SetValue("vid_window_x", v);
        else if (sscanf(line, "vid_window_y \"%f", &v) == 1)     Cvar_SetValue("vid_window_y", v);
        else if (sscanf(line, "vid_window_w \"%f", &v) == 1)     Cvar_SetValue("vid_window_w", v);
        else if (sscanf(line, "vid_window_h \"%f", &v) == 1)     Cvar_SetValue("vid_window_h", v);
        else if (sscanf(line, "vid_scale \"%f", &v) == 1)        Cvar_SetValue("vid_scale", v);
        else if (sscanf(line, "vid_supersample \"%f", &v) == 1)         Cvar_SetValue("vid_supersample", v);
        else if (sscanf(line, "vid_scanlines \"%f", &v) == 1)           Cvar_SetValue("vid_scanlines", v);
        else if (sscanf(line, "vid_scanline_intensity \"%f", &v) == 1)  Cvar_SetValue("vid_scanline_intensity", v);
        else if (sscanf(line, "vid_scanline_size \"%f", &v) == 1)       Cvar_SetValue("vid_scanline_size", v);
    }
    fclose(f);
}

void VID_Init(unsigned char *palette)
{
    Cvar_RegisterVariable(&vid_scale);
    Cvar_RegisterVariable(&vid_window_scale);
    Cvar_RegisterVariable(&vid_window_x);
    Cvar_RegisterVariable(&vid_window_y);
    Cvar_RegisterVariable(&vid_window_w);
    Cvar_RegisterVariable(&vid_window_h);
    Cvar_RegisterVariable(&vid_supersample);
    Cvar_RegisterVariable(&vid_scanlines);
    Cvar_RegisterVariable(&vid_scanline_intensity);
    Cvar_RegisterVariable(&vid_scanline_size);

    Video_Record_Init();

    vid_preload_cvars_from_config();

    {
        // Auto-detect the largest integer scale that fits the desktop; used
        // as fallback for both render and window when their cvars are unset.
        // Headless has no display to query, so fall back to 1x — the smallest
        // framebuffer the software renderer (and MCP screenshots) still work on.
        int auto_scale = 1;
        if (!sys_headless)
        {
            auto_scale = 3;
            SDL_DisplayID display = SDL_GetPrimaryDisplay();
            SDL_Rect usable;
            if (SDL_GetDisplayUsableBounds(display, &usable))
            {
                int sx = usable.w / VID_WIDTH;
                int sy = usable.h / VID_HEIGHT;
                auto_scale = sx < sy ? sx : sy;
                if (auto_scale < 1) auto_scale = 1;
                if (auto_scale > 4) auto_scale = 4;
            }
        }

        int render_req = (int)vid_scale.value;
        int render_scale = (render_req >= 1 && render_req <= 4) ? render_req : auto_scale;

        int window_req = (int)vid_window_scale.value;
        int window_scale = (window_req >= 1 && window_req <= 4) ? window_req : auto_scale;

        int ss_req = (int)vid_supersample.value;
        int ss = (ss_req >= 1 && ss_req <= 4) ? ss_req : 1;
        while (render_scale * ss > 8 && ss > 1) ss--;

        vid_scale_active        = render_scale;
        vid_supersample_active  = ss;
        vid_window_scale_active = window_scale;
        vid_render_w            = VID_WIDTH  * render_scale;
        vid_render_h            = VID_HEIGHT * render_scale;
        vid_super_w             = vid_render_w * ss;
        vid_super_h             = vid_render_h * ss;

        // Window + GPU device. Skipped entirely when headless — vid.buffer is
        // still filled below, so CPU-side software rendering and MCP screenshots
        // keep working; only the on-screen present is gone (VID_Update early-outs
        // on a NULL gpu_device).
        if (!sys_headless)
        {
            int wx = (int)vid_window_x.value;
            int wy = (int)vid_window_y.value;
            int saved_w = (int)vid_window_w.value;
            int saved_h = (int)vid_window_h.value;
            int ww = (saved_w >= 1) ? saved_w : VID_WIDTH  * window_scale;
            int wh = (saved_h >= 1) ? saved_h : VID_HEIGHT * window_scale;
            SDL_PropertiesID props = SDL_CreateProperties();
            SDL_SetStringProperty(props, SDL_PROP_WINDOW_CREATE_TITLE_STRING, "quake1.ai");
            SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER, ww);
            SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER, wh);
            SDL_SetBooleanProperty(props, SDL_PROP_WINDOW_CREATE_RESIZABLE_BOOLEAN, true);
            if (wx >= 0 && wy >= 0)
            {
                SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_X_NUMBER, wx);
                SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_Y_NUMBER, wy);
            }
            // -nofocus: don't let the window grab keyboard focus when it first
            // appears, so launching from a terminal doesn't interrupt the user.
            // Only affects the initial show — clicking the window focuses it.
            if (sys_nofocus)
                SDL_SetHint(SDL_HINT_WINDOW_ACTIVATE_WHEN_SHOWN, "0");
            sdl_window = SDL_CreateWindowWithProperties(props);
            SDL_DestroyProperties(props);
            if (!sdl_window)
                Sys_Error("SDL_CreateWindow failed: %s", SDL_GetError());

            if (!gpu_init(sdl_window))
                Sys_Error("GPU init failed");
        }
    }

    // Fill in viddef
    memset(&vid, 0, sizeof(vid));
    vid.width      = vid_super_w;
    vid.height     = vid_super_h;
    vid.rowbytes   = vid_super_w;
    // Pixel aspect for 4:3 CRT at 320x200 — scale-independent since w and h
    // scale by the same factor, preserving the ratio.
    vid.aspect     = ((float)VID_HEIGHT / (float)VID_WIDTH) * (320.0f / 240.0f);
    vid.numpages   = 1;
    vid.colormap   = host_colormap;
    vid.fullbright = 256 - LittleLong(*((int *)vid.colormap + 2048));
    vid.buffer     = vid_buffer;
    vid.conbuffer  = vid_buffer;
    vid.conwidth   = vid_super_w;
    vid.conheight  = vid_super_h;
    vid.conrowbytes = vid_super_w;
    vid.maxwarpwidth  = WARP_WIDTH;
    vid.maxwarpheight = WARP_HEIGHT;
    vid.recalc_refdef = 1;

    build_palette(palette);
    vid_load_aux_palette(VID_PAL_DOOM, "gfx/palette_doom.lmp");

    if (!sys_headless)
    {
        ImguiLayer_Init(sdl_window, gpu_device, gpu_swapchain_format);
        RBBox_Init();
        RPaths_Init();
    }

    // Allocate z-buffer and surface cache from the hunk (as vid_win.c does)
    {
        extern short *d_pzbuffer;
        extern int    D_SurfaceCacheForRes(int w, int h);
        extern void   D_InitCaches(void *buffer, int size);
        extern void  *Hunk_HighAllocName(int size, char *name);

        // Pre-allocate for max resolution so VID_ApplyResolution never needs hunk realloc.
        int zbuf_bytes_max  = VID_RENDER_MAX_W * VID_RENDER_MAX_H * sizeof(short);
        int cache_bytes_max = D_SurfaceCacheForRes(VID_RENDER_MAX_W, VID_RENDER_MAX_H);
        d_pzbuffer = (short *)Hunk_HighAllocName(zbuf_bytes_max + cache_bytes_max, "video");

        int zbuf_bytes  = vid_super_w * vid_super_h * sizeof(short);
        int cache_bytes = D_SurfaceCacheForRes(vid_super_w, vid_super_h);
        D_InitCaches((byte *)d_pzbuffer + zbuf_bytes, cache_bytes);
    }

    vid_menu_cursor = VID_MENU_RENDER_BASE + (vid_scale_active - 1);
    vid_menudrawfn  = VID_MenuDraw;
    vid_menukeyfn   = VID_MenuKey;
}

void VID_Shutdown(void)
{
    Video_Record_Shutdown();
    ImguiLayer_Shutdown();
    gpu_shutdown();
    if (sdl_window) { SDL_DestroyWindow(sdl_window); sdl_window = NULL; }
}

// ---------------------------------------------------------------------------
// Window title: "quake1.ai — <game|editor> — <map>"
// ---------------------------------------------------------------------------
//
// Rebuilt every frame (cheap: snprintf + strcmp); SDL_SetWindowTitle only
// fires when the string actually changes. Map name uses the MCP server's
// canonical source (sv.name while a local server is active); with no map
// loaded — i.e. the main menu — we fall back to the bare "quake1.ai".
static void vid_update_window_title(void)
{
    if (!sdl_window) return;

    const char *mode = Editor_IsOpen() ? "editor" : "game";
    const char *map  = (sv.active && sv.name[0]) ? sv.name : NULL;

    char title[160];
    if (map)
        SDL_snprintf(title, sizeof(title), "quake1.ai \xe2\x80\x94 %s \xe2\x80\x94 %s", mode, map);
    else
        SDL_strlcpy(title, "quake1.ai", sizeof(title));

    static char last[160];
    if (SDL_strcmp(title, last) != 0)
    {
        SDL_SetWindowTitle(sdl_window, title);
        SDL_strlcpy(last, title, sizeof(last));
    }
}

// ---------------------------------------------------------------------------
// Frame update: expand 8-bit -> 32-bit, upload, present
// ---------------------------------------------------------------------------

void VID_Update(vrect_t *rects)
{
    (void)rects;
    if (!gpu_device) return;

    vid_update_window_title();

    Crop_FrameStart();

    RPaths_Draw();
    RBBox_Draw();
    // DebugLines_Draw() moved into R_RenderView_ (between world and entities)
    // so monsters / items naturally overdraw debug lines. Bbox / path overlays
    // stay here — they're meant to sit on top of entities.

    gpu_render_frame();

    // Capture this frame to a video if recording. vid.buffer still holds the
    // 8-bit indices gpu_render_frame just consumed.
    Video_Record_CaptureFrame();

    // Reset palette tags so the next frame's renderer starts clean. Runs
    // unconditionally (even if SDL_LockTexture failed) to preserve the
    // invariant: palette_id is always zero at the start of every frame's
    // renderer pipeline. Must run AFTER the expand step (above) which
    // reads the tags this frame's renderer wrote — clearing earlier
    // would wipe those tags before expand sees them.
    memset(vid_palette_id, 0, vid_super_w * vid_super_h);

    // Force the sbar to redraw on the next SCR_UpdateScreen. Stock Quake
    // uses sb_updates / vid.numpages to skip Sbar_Draw once each VRAM page
    // has the latest sbar — an optimization that assumed the front buffer
    // and back buffer kept stable copies between flips. Our SDL backend
    // re-uploads vid.buffer wholesale every frame, so any region not
    // explicitly redrawn this frame keeps whatever the previous renderer
    // wrote there — most visibly, a bobbing viewmodel sprite writing pixels
    // under the sbar. Resetting sb_updates here makes Sbar_Draw redraw
    // every frame; the redraw cost is a couple of paletted blits and is
    // negligible compared to the framebuffer expand+upload above.
    Sbar_Changed();
}

int VID_SetMode(int modenum, unsigned char *palette)
{
    (void)modenum;
    build_palette(palette);
    return 1;
}

void VID_HandlePause(qboolean pause) { (void)pause; }

// Stubs for DirectDraw surface locking (no-ops in SDL version)
int  VID_ForceUnlockedAndReturnState(void) { return 0; }
void VID_ForceLockState(int lk)            { (void)lk; }
void VID_SetDefaultMode(void)              {}

// On Windows quakedef.h declares VID_Lock/UnlockBuffer as real functions;
// on POSIX they're empty macros, so defining them here would expand to
// `void  (void) {}`.
#if defined(_WIN32) && !defined(WINDED)
void VID_LockBuffer(void)   {}
void VID_UnlockBuffer(void) {}
#endif

SDL_Window    *VID_GetWindow   (void) { return sdl_window; }
SDL_GPUDevice *VID_GetGPUDevice(void) { return gpu_device; }
int            VID_SupersampleActive(void) { return vid_supersample_active; }
// VID_GetRenderer kept as a no-op stub during transition for any stragglers
// that still expect the old SDL_Renderer-returning API. New code should use
// VID_GetGPUDevice() instead.
SDL_Renderer  *VID_GetRenderer (void) { return NULL; }

// Map a mouse-event window pixel coord into framebuffer / logical coords.
// Matches the integer-scale letterbox the GPU present uses: window (wx,wy)
// outside the viewport returns the nearest clamped logical pixel. The crop
// screenshot tool uses this to translate drag endpoints into vid.buffer-
// space rectangles.
void VID_WindowToLogical(float wx, float wy, float *lx, float *ly)
{
    int win_w = 0, win_h = 0;
    if (sdl_window) SDL_GetWindowSize(sdl_window, &win_w, &win_h);
    if (win_w <= 0 || win_h <= 0 || vid_render_w <= 0 || vid_render_h <= 0) {
        if (lx) *lx = wx;
        if (ly) *ly = wy;
        return;
    }
    // Integer-scale aspect-preserving letterbox, identical to gpu_render_frame.
    int sx = win_w / vid_render_w;
    int sy = win_h / vid_render_h;
    int int_scale = sx < sy ? sx : sy;
    if (int_scale < 1) int_scale = 1;
    int vp_w = vid_render_w * int_scale;
    int vp_h = vid_render_h * int_scale;
    float vp_x = (float)((win_w - vp_w) / 2);
    float vp_y = (float)((win_h - vp_h) / 2);
    if (lx) *lx = (wx - vp_x) / (float)int_scale;
    if (ly) *ly = (wy - vp_y) / (float)int_scale;
}

// Loading disc overlays — not needed with SDL renderer
void D_BeginDirectRect(int x, int y, byte *pbitmap, int width, int height)
    { (void)x; (void)y; (void)pbitmap; (void)width; (void)height; }
void D_EndDirectRect(int x, int y, int width, int height)
    { (void)x; (void)y; (void)width; (void)height; }

// ---------------------------------------------------------------------------
// png_buf_t / png_buf_append -- growable byte buffer used as the write target
// for stbi_write_png_to_func so that we hold the encoded PNG in memory before
// deciding what to do with it (write file, copy to clipboard, etc.).
// ---------------------------------------------------------------------------
typedef struct {
    unsigned char *data;
    size_t         size;
    size_t         cap;
} png_buf_t;

static void png_buf_append(void *ctx, void *data, int len)
{
    png_buf_t *b = (png_buf_t *)ctx;
    if (len <= 0) return;
    size_t need = b->size + (size_t)len;
    if (need > b->cap) {
        size_t new_cap = b->cap ? b->cap * 2 : 4096;
        while (new_cap < need) new_cap *= 2;
        unsigned char *p = (unsigned char *)realloc(b->data, new_cap);
        if (!p) return;   /* writing stops; final size != need will be caught */
        b->data = p;
        b->cap  = new_cap;
    }
    memcpy(b->data + b->size, data, (size_t)len);
    b->size = need;
}

// ---------------------------------------------------------------------------
// ---------------------------------------------------------------------------
// vid_encode_screenshot_png -- palette-expand vid.buffer to RGB, encode as
// PNG bytes into heap memory. On success, *out_bytes / *out_size are filled
// and the caller is responsible for free()ing *out_bytes. Returns 1 on ok.
// ---------------------------------------------------------------------------
static int vid_encode_screenshot_png(unsigned char **out_bytes, size_t *out_size)
{
    int w, h, rowbytes, y, x, ok;
    unsigned char *rgb;
    png_buf_t buf;

    *out_bytes = NULL;
    *out_size  = 0;
    if (!vid.buffer) return 0;

    w        = (int)vid.width;
    h        = (int)vid.height;
    rowbytes = (int)vid.rowbytes;
    if (w <= 0 || h <= 0 || rowbytes < w) return 0;

    rgb = (unsigned char *)malloc((size_t)w * (size_t)h * 3);
    if (!rgb) return 0;
    for (y = 0; y < h; y++) {
        const byte    *src = vid.buffer + y * rowbytes;
        unsigned char *dst = rgb        + y * w * 3;
        for (x = 0; x < w; x++) {
            unsigned c = d_8to24table[src[x]];
            dst[x*3 + 0] = (unsigned char)(c >> 16);
            dst[x*3 + 1] = (unsigned char)(c >>  8);
            dst[x*3 + 2] = (unsigned char)(c >>  0);
        }
    }

    memset(&buf, 0, sizeof(buf));
    ok = stbi_write_png_to_func(png_buf_append, &buf, w, h, 3, rgb, w * 3);
    free(rgb);
    if (!ok || !buf.data) { free(buf.data); return 0; }
    *out_bytes = buf.data;
    *out_size  = buf.size;
    return 1;
}

static int vid_write_file(const char *path, const unsigned char *bytes, size_t size)
{
    FILE *fp;
    size_t wrote;
    fp = fopen(path, "wb");
    if (!fp) return 0;
    wrote = fwrite(bytes, 1, size, fp);
    fclose(fp);
    return wrote == size;
}

// ---------------------------------------------------------------------------
// VID_SaveScreenshotPNG -- write the current 8-bit framebuffer as a 24-bit
// PNG. Returns 1 on success, 0 on failure. Caller is responsible for the
// destination directory existing.
// ---------------------------------------------------------------------------
int VID_SaveScreenshotPNG(const char *path)
{
    unsigned char *bytes = NULL;
    size_t size = 0;
    int ok;
    if (!path || !path[0]) return 0;
    if (!vid_encode_screenshot_png(&bytes, &size)) return 0;
    ok = vid_write_file(path, bytes, size);
    free(bytes);
    return ok;
}

// ---------------------------------------------------------------------------
// VID_SaveScreenshotPNG_AndClip -- write the current framebuffer to `path`
// and, if `also_clipboard` is nonzero, push the same PNG bytes to the system
// clipboard. Returns a bitfield: bit 0 = file write ok, bit 1 = clipboard ok
// (only set when also_clipboard was nonzero).
// ---------------------------------------------------------------------------
int VID_SaveScreenshotPNG_AndClip(const char *path, int also_clipboard)
{
    unsigned char *bytes = NULL;
    size_t size = 0;
    int result = 0;
    if (!path || !path[0]) return 0;
    if (!vid_encode_screenshot_png(&bytes, &size)) return 0;
    if (vid_write_file(path, bytes, size)) result |= 1;
    if (also_clipboard && Clipboard_SetPNG(bytes, size)) result |= 2;
    free(bytes);
    return result;
}

// ---------------------------------------------------------------------------
// VID_SamplePixel -- read a single framebuffer pixel. Returns 1 on success,
// 0 if (x,y) is out of bounds or vid.buffer is NULL. Out params receive the
// RGB triple from d_8to24table[] and the raw 8-bit palette index.
// ---------------------------------------------------------------------------
int VID_SamplePixel(int x, int y, byte *r, byte *g, byte *b, byte *idx)
{
    if (!vid.buffer) return 0;
    if (x < 0 || y < 0) return 0;
    if (x >= (int)vid.width || y >= (int)vid.height) return 0;

    byte i = vid.buffer[y * (int)vid.rowbytes + x];
    unsigned c = d_8to24table[i];
    /* d_8to24table is 0xAARRGGBB; pulling R from bits 16..23, not bits 0..7. */
    if (r)   *r   = (byte)(c >> 16);
    if (g)   *g   = (byte)(c >>  8);
    if (b)   *b   = (byte)(c >>  0);
    if (idx) *idx = i;
    return 1;
}
